// flow-typed signature: 1686125f3e7db3da6fb379e943c37294
// flow-typed version: <<STUB>>/hops-build_v7.2.0/flow_v0.57.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hops-build'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hops-build' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hops-build/build' {
  declare module.exports: any;
}

declare module 'hops-build/lib/cleanup' {
  declare module.exports: any;
}

declare module 'hops-build/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hops-build/build.js' {
  declare module.exports: $Exports<'hops-build/build'>;
}
declare module 'hops-build/index' {
  declare module.exports: $Exports<'hops-build'>;
}
declare module 'hops-build/index.js' {
  declare module.exports: $Exports<'hops-build'>;
}
declare module 'hops-build/lib/cleanup.js' {
  declare module.exports: $Exports<'hops-build/lib/cleanup'>;
}
declare module 'hops-build/server.js' {
  declare module.exports: $Exports<'hops-build/server'>;
}
