// flow-typed signature: eb1b8621ac9603dd3c34df1874cf3cd6
// flow-typed version: <<STUB>>/hops-local-cli_v9.3.0/flow_v0.57.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hops-local-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hops-local-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hops-local-cli/commands/start' {
  declare module.exports: any;
}

declare module 'hops-local-cli/init' {
  declare module.exports: any;
}

declare module 'hops-local-cli/lib/commands' {
  declare module.exports: any;
}

declare module 'hops-local-cli/lib/package-manager' {
  declare module.exports: any;
}

declare module 'hops-local-cli/run' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hops-local-cli/commands/start.js' {
  declare module.exports: $Exports<'hops-local-cli/commands/start'>;
}
declare module 'hops-local-cli/index' {
  declare module.exports: $Exports<'hops-local-cli'>;
}
declare module 'hops-local-cli/index.js' {
  declare module.exports: $Exports<'hops-local-cli'>;
}
declare module 'hops-local-cli/init.js' {
  declare module.exports: $Exports<'hops-local-cli/init'>;
}
declare module 'hops-local-cli/lib/commands.js' {
  declare module.exports: $Exports<'hops-local-cli/lib/commands'>;
}
declare module 'hops-local-cli/lib/package-manager.js' {
  declare module.exports: $Exports<'hops-local-cli/lib/package-manager'>;
}
declare module 'hops-local-cli/run.js' {
  declare module.exports: $Exports<'hops-local-cli/run'>;
}
