// flow-typed signature: e1ed6b9b7417b36697ab09aa2ebb27b5
// flow-typed version: <<STUB>>/hops-express_v7.2.0/flow_v0.57.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hops-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hops-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hops-express/app' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hops-express/app.js' {
  declare module.exports: $Exports<'hops-express/app'>;
}
declare module 'hops-express/index' {
  declare module.exports: $Exports<'hops-express'>;
}
declare module 'hops-express/index.js' {
  declare module.exports: $Exports<'hops-express'>;
}
