// flow-typed signature: 75811a45d5df9fbbfdd0bc7a071ca130
// flow-typed version: <<STUB>>/hops-config_v7.2.0/flow_v0.57.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hops-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hops-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hops-config/lib/manifest-util' {
  declare module.exports: any;
}

declare module 'hops-config/lib/parse-env' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hops-config/index' {
  declare module.exports: $Exports<'hops-config'>;
}
declare module 'hops-config/index.js' {
  declare module.exports: $Exports<'hops-config'>;
}
declare module 'hops-config/lib/manifest-util.js' {
  declare module.exports: $Exports<'hops-config/lib/manifest-util'>;
}
declare module 'hops-config/lib/parse-env.js' {
  declare module.exports: $Exports<'hops-config/lib/parse-env'>;
}
