// flow-typed signature: c5d3276b1c35def5f37f6a44d076eabc
// flow-typed version: <<STUB>>/hops-redux_v7.2.0/flow_v0.57.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hops-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hops-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'hops-redux/index' {
  declare module.exports: $Exports<'hops-redux'>;
}
declare module 'hops-redux/index.js' {
  declare module.exports: $Exports<'hops-redux'>;
}
