// flow-typed signature: 4399e413902aef997f547c153b3d078e
// flow-typed version: <<STUB>>/hops-react_v7.2.0/flow_v0.57.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hops-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hops-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hops-react/dom' {
  declare module.exports: any;
}

declare module 'hops-react/lib/common' {
  declare module.exports: any;
}

declare module 'hops-react/lib/components' {
  declare module.exports: any;
}

declare module 'hops-react/lib/template' {
  declare module.exports: any;
}

declare module 'hops-react/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hops-react/dom.js' {
  declare module.exports: $Exports<'hops-react/dom'>;
}
declare module 'hops-react/lib/common.js' {
  declare module.exports: $Exports<'hops-react/lib/common'>;
}
declare module 'hops-react/lib/components.js' {
  declare module.exports: $Exports<'hops-react/lib/components'>;
}
declare module 'hops-react/lib/template.js' {
  declare module.exports: $Exports<'hops-react/lib/template'>;
}
declare module 'hops-react/node.js' {
  declare module.exports: $Exports<'hops-react/node'>;
}
