// flow-typed signature: e4f98c433f0dce9806e2ed78fdc3bde7
// flow-typed version: <<STUB>>/jest-preset-hops_v7.2.0/flow_v0.57.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-preset-hops'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-preset-hops' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-preset-hops/file-mock' {
  declare module.exports: any;
}

declare module 'jest-preset-hops/tpl-mock' {
  declare module.exports: any;
}

declare module 'jest-preset-hops/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-preset-hops/file-mock.js' {
  declare module.exports: $Exports<'jest-preset-hops/file-mock'>;
}
declare module 'jest-preset-hops/tpl-mock.js' {
  declare module.exports: $Exports<'jest-preset-hops/tpl-mock'>;
}
declare module 'jest-preset-hops/transform.js' {
  declare module.exports: $Exports<'jest-preset-hops/transform'>;
}
